### ISSUE TITLE
那我该如何接收resolve和reject的参数呢

### ISSUE THREAD

**Issue by AuTsing** [mmc1993/Lua-Async#1]
那我该如何接收resolve和reject的参数呢

**Comment by mmc1993** [comment]
通过Ok和No两个函数进入到不同的下一分支.
同时Ok和No可传递参数到下一分支.
分支函数是 Func(Ok, No, ...)
后面省略部分是Ok或者No传递的参数.
例:
Ok(arg1, arg2) -- 在这里进入Ok分支并传递两个参数.

Func(Ok, No, arg1, arg2) -- 在这个分支函数中收到上流传递的两个参数.
